- name: Verificar as bibliotecas necessarias para o PostgreSQL foram instaladas.
  apt:
    name: "{{ postgresql_python_library }}"
    state: present

- name:  Verificar se os pacotes do PostgreSQL foram instalados.
  apt:
    name: "{{ postgresql_packages }}"
    state: present

- name: Verificar os códigos de idioma.
  locale_gen: "name={{ item }} state=present"
  with_items: "{{ postgresql_locales }}"
  register: locale_gen_result

- name: Força o reinício do Postgre.
  service:
    name: "{{ postgresql_daemon }}"
    state: restarted
  when: locale_gen_result.changed